apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURndwpNRFExTVRWYUZ3MDBNakE0TURnd01EUTFNVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdHBhbWhrZDZJb2lNendDQksvNEh5a0gyQW9DMjZXMHliMnR2cnVKRkUwQ1d4amdBNgo2cjk0NGhrMHFNWnNlSDhXUVIvOWxNTExhY2M0QXpuYThTb3AyVDlreVpubDUxNEhiWC9NcEZwZDA5REFqU0FoCjN5QithRU8xQ0dGeVZrWDdTL09zcUJGNHlSR1VvRmdVRUVqRVJzSFVEK2tlajZtVjBoa1A1UFlkMEtJc1Rxa2gKSWgrNzg0aFpycGVpUGIrcUdYWHVGVWZ4bDVNc29VQUJ5QUJCNWxNdlgyZkdoNFRCaWRydU55WkN0STYrRnZQMQozUE1FYWxtRnNlN21ScHNWWEtCeVBqQ216QmJ0bjNEL0lUTy9nbUl0VnlEbHJYRW04alFnUjFlRVZRZUU4cGt4CndWdUplOVZqMmpicDFPSHJXWGYra2dab1hCRDR1ZlMyaHRBTkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlF6em5qbXpST05iZktDUG9PNQp3YWc0VTdGUEZqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGWEJHa1dSOG5VclJtTGdQSTgvNmE3VnFZUXpHClhXVFgySjlLaXJYdVlBNkdEcDJNTHJvQzZsQlRTSkZmZUFGRkplTXY4anFZL1c0YWczNGpYSVVWa2pOaFpGZjAKdGtPMVRnTWdmWFlVVGtIZ0ttN0pQUW1tY3lFdFdBcC94OHJzTE82NnF4NXM5aEVkYkNMWDN6d1RsT0lDOXZMNgpPMS9kK1V4ZzROS2kzWmE1MkVoYmxBdU5oL2xBM2RjckFvK01hOXgxTFBlTTl4UldHM0lSNzlHWjVkNmMxQnltCmtqZVlJRzVkR3B3Mis2WWp6YSs4U0ZyRkJ0NHFRNS9jYVNNZWkvSXg1UVJEcHZpL1dLKzM5dkoyZVZabjgyblAKNHJXajBOa0x5WHBpdnoxRGVzVFZTSU42Ly8xdWFZWGRsdmNGTUZhOUJKSDZqSUlDaG1wUWdMV3dYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://96f30fb2-ccec-4f2d-8fc2-3e9a235b86e4.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa
    user: do-nyc1-k8s-iniciativa-admin
  name: do-nyc1-k8s-iniciativa
current-context: do-nyc1-k8s-iniciativa
users:
- name: do-nyc1-k8s-iniciativa-admin
  user:
    token: dop_v1_7911e98039f035b5fd092404a2477b48d8b6b9c126e528d349630630935c90c1
